#!/bin/sh
#
# Get the stuff from lab 4
# Copy C++ source files, but make soft links to data files.
#
	N=4
	LABFILES=/comp/11/files/lab$N

	WHERE=`pwd | tr '[A-Z]' '[a-z]'`
	case $WHERE in
		*lab*$N)	;;
		*)	echo "Please run this from your lab$N folder"
			exit 1
			;;
	esac

	cp $LABFILES/*.cpp .
	ln -s $LABFILES/*.bd .
